package com.jypmis.func.login;

//Generated by MyEclipse

public interface ILogin {

	/**
	 * 用户登录函数，手机端函数
	 * @param username
	 * @param password
	 * @return
	 */
	public String login(String username, String password);
}