package com.jypmis.func.report;
//Generated by MyEclipse
import java.util.List;

import com.jypmis.po.Bbg;
import com.jypmis.po.Sbgx;
public interface IReport {
	
	/**
	 * 新增报工，手机端函数
	 * @param userid
	 * @param reportStr报工信息json格式的字符串
	 * @return
	 */
	public String saveReport(String userid, String reportStr);

	/***
	 * 删除报工，手机端函数
	 * @param reportid
	 * @return
	 */
	public String deleteReport(String reportid);

	/***
	 * 修改报工，手机端函数
	 * 
	 * @param workdate
	 * @param reporttype
	 * @param reportproject
	 * @param reportplace
	 * @param workhour
	 * @param workcontent
	 * @return
	 */
	public String updateReport(String yhid,String reportStr,String type);

	/***
	 * 获取报工内容，手机端函数
	 * 
	 * @param reportid
	 * @return
	 */
	public String showReport(String bgid);

	/**
	 * 查询报工条数，手机函数
	 * 用户在登陆主页上显示提示数字
	 * @param yhid
	 * @param zt
	 * @return
	 */
	public int getReportCount(String yhid,String zt);
	
	/***
	 * 查询报工,手机端函数
	 * 根据输入的搜索条件查询报工
	 */
	public String getReports(String  reportSearchFieldStr);

	/**
	 * 报工类型，手机端函数
	 * @return
	 */
	public String getReportTypes();
	
	/**
	 * 查询报工项,为报工类型提供列表
	 * @return
	 */
	public List<Sbgx> findReportTypes();
	
	/**
	 * 查询报工，根据报工id：bgid
	 * @param bgid
	 * @return
	 */
	public List<Bbg> findReportByID(String bgid);
	
	/**
	 * 查询报工，根据搜索条件进行查询
	 * @param reportSearchFieldStr 搜索条件
	 * @return
	 */
	public List<Bbg> findReportBySearchStr(String reportSearchFieldStr);
}